/* Fe'l tarjimalari — manba PDF'da yo'q, qo'lda yozildi. */

export const VERB_UZ = {
  брать: "olmoq",
  быть: "bo'lmoq",
  вешать: "osmoq, ilmoq",
  видеть: "ko'rmoq",
  "возвращать(ся)": "qaytarmoq / qaytmoq",
  выбирать: "tanlamoq",
  выздоравливать: "tuzalmoq, sog'aymoq",
  выпускать: "chiqarmoq, ishlab chiqarmoq",
  выращивать: "o'stirmoq, yetishtirmoq",
  говорить: "gapirmoq / aytmoq",
  "готовить(ся)": "tayyorlamoq / tayyorlanmoq",
  давать: "bermoq",
  доставать: "olmoq, yetib olmoq",
  есть: "yemoq",
  запрещать: "taqiqlamoq",
  "знакомить(ся)": "tanishtirmoq / tanishmoq",
  изображать: "tasvirlamoq",
  "интересовать(ся)": "qiziqtirmoq / qiziqmoq",
  класть: "qo'ymoq (yotqizib)",
  мочь: "qila olmoq",
  награждать: "mukofotlamoq",
  "называть(ся)": "atamoq / atalmoq",
  находиться: "joylashgan bo'lmoq",
  "начинать(ся)": "boshlamoq / boshlanmoq",
  "оказывать(ся)": "ko'rsatmoq / bo'lib chiqmoq",
  отвечать: "javob bermoq",
  отдыхать: "dam olmoq",
  отказываться: "voz kechmoq, rad etmoq",
  "открывать(ся)": "ochmoq / ochilmoq",
  отправлять: "jo'natmoq",
  передавать: "uzatmoq, yetkazmoq",
  петь: "kuylamoq",
  писать: "yozmoq",
  пить: "ichmoq",
  поздравлять: "tabriklamoq",
  "поднимать(ся)": "ko'tarmoq / ko'tarilmoq",
  показывать: "ko'rsatmoq",
  покупать: "sotib olmoq",
  помогать: "yordam bermoq",
  посещать: "tashrif buyurmoq",
  поступать: "kirmoq (o'qishga)",
  посылать: "yubormoq",
  преподавать: "dars bermoq",
  присылать: "yuborib bermoq",
  провожать: "kuzatmoq",
  производить: "ishlab chiqarmoq",
  просить: "so'ramoq, iltimos qilmoq",
  прощать: "kechirmoq",
  "радовать(ся)": "xursand qilmoq / xursand bo'lmoq",
  "развивать(ся)": "rivojlantirmoq / rivojlanmoq",
  рассказывать: "hikoya qilmoq, so'zlab bermoq",
  рисовать: "rasm chizmoq",
  садиться: "o'tirmoq",
  сдавать: "topshirmoq (imtihon)",
  советовать: "maslahat bermoq",
  создавать: "yaratmoq",
  составлять: "tuzmoq",
  ставить: "qo'ymoq (tik)",
  трудиться: "mehnat qilmoq",
  увлекаться: "qiziqib qolmoq, berilib ketmoq",
  умирать: "o'lmoq, vafot etmoq",
  устанавливать: "o'rnatmoq",
  хотеть: "xohlamoq",
};
